project_id = "ulwatxrssexhbxuhapbb"

[functions.send-welcome-email]
verify_jwt = false

[functions.sync-express-entry]
verify_jwt = false

[functions.sync-express-entry-v2]
verify_jwt = false

[functions.api-draws]
verify_jwt = false

[functions.api-draws-series]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true
