// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulwatxrssexhbxuhapbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsd2F0eHJzc2V4aGJ4dWhhcGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjY2MzcsImV4cCI6MjA3MzA0MjYzN30.Vd6UM-XZs3lRC-kt2lPKhdI7WARyN-tPdev06h2uJRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});